plugins {
    id "com.gradleup.shadow"
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    mixin {
        useLegacyMixinAp = true
        add(sourceSets.main, "quickstackcraft-forge-refmap.json")
    }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven { url = "https://maven.minecraftforge.net/" }
}

dependencies {
    forge "net.minecraftforge:forge:${rootProject.minecraft_version}-${rootProject.forge_version}"

    // Architectury API (Forge)
    modApi "dev.architectury:architectury-forge:${rootProject.architectury_api_version}"

    // JEI (compile-only)
    modCompileOnlyApi "mezz.jei:jei-${rootProject.minecraft_version}-forge-api:${rootProject.jei_version}"

    // EMI (compile-only)
    modCompileOnlyApi "dev.emi:emi-forge:${rootProject.emi_version}:api"

    common(project(path: ":common", configuration: "namedElements")) { transitive = false }
    shadowBundle project(path: ":common", configuration: "transformProductionForge")
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

jar { manifest.attributes("MixinConfigs": "quickstackcraft-common.mixins.json,quickstackcraft.mixins.json") }
